# Generated by Django 5.2.2 on 2025-06-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0007_alter_empresa_logo_alter_equipo_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('empresa', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(max_length=100)),
                ('descripcion_empresa', models.TextField(help_text='Breve descripción de su empresa y actividades')),
                ('motivo', models.TextField(help_text='¿Por qué desea ser socio?')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('notas_admin', models.TextField(blank=True, help_text='Notas internas para administradores', null=True)),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
