# Generated by Django 5.2.2 on 2025-06-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0008_socio'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('puesto_deseado', models.CharField(max_length=100, verbose_name='Puesto Deseado')),
                ('experiencia_relevante', models.TextField(verbose_name='Experiencia Relevante')),
                ('mensaje_presentacion', models.TextField(verbose_name='Mensaje de Presentación')),
                ('cv', models.FileField(help_text='PDF o Word (máx. 5MB)', upload_to='cvs/', verbose_name='CV')),
                ('fecha_aplicacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aplicación de Trabajo',
                'verbose_name_plural': 'Aplicaciones de Trabajo',
                'ordering': ['-fecha_aplicacion'],
            },
        ),
    ]
