# Generated by Django 5.2.2 on 2025-06-16 02:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0009_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='cv',
            field=cloudinary.models.CloudinaryField(help_text='PDF o Word (máx. 5MB)', max_length=255),
        ),
    ]
