# Generated by Django 5.2.2 on 2025-06-16 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0010_alter_jobapplication_cv'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('es_administrador', models.BooleanField(default=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cc.empresa')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario de Empresa',
                'verbose_name_plural': 'Usuarios de Empresas',
            },
        ),
    ]
