# Generated by Django 5.2.2 on 2025-06-16 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0011_empresausuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresausuario',
            options={'ordering': ['-fecha_asignacion'], 'verbose_name': 'Usuario de Empresa', 'verbose_name_plural': 'Usuarios de Empresas'},
        ),
        migrations.RemoveField(
            model_name='empresausuario',
            name='es_administrador',
        ),
        migrations.AlterField(
            model_name='empresausuario',
            name='empresa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cc.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='empresausuario',
            name='fecha_asignacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de asignación'),
        ),
        migrations.AlterField(
            model_name='empresausuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
