# Generated by Django 5.1.11 on 2025-06-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0012_alter_empresausuario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='sitio_web',
            field=models.URLField(blank=True, null=True, verbose_name='Red Social'),
        ),
    ]
