# Generated by Django 5.1.11 on 2025-07-25 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0013_alter_empresa_sitio_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='facebook',
            field=models.CharField(blank=True, default='https://www.facebook.com/', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='instagram',
            field=models.CharField(blank=True, default='https://www.instagram.com/', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='linkedin',
            field=models.CharField(blank=True, default='https://www.linkedin.com/', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tiktok',
            field=models.CharField(blank=True, default='https://www.tiktok.com/', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='twitter',
            field=models.CharField(blank=True, default='https://www.twitter.com/', max_length=100, null=True),
        ),
    ]
