# Generated by Django 5.1.11 on 2025-07-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0014_empresa_facebook_empresa_instagram_empresa_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ruc',
            field=models.CharField(blank=True, default='1234567890001', max_length=13, null=True),
        ),
    ]
