# Generated by Django 5.1.11 on 2025-07-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0015_empresa_ruc'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='cedula',
            field=models.CharField(blank=True, default='1234567890', max_length=20, null=True, unique=True, verbose_name='Cédula'),
        ),
    ]
